networks:
  event-world-network:
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      target: builder
    volumes:
      - ./backend/app:/app
    env_file:
      - .env
    restart: "no"
    networks:
      - event-world-network
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    env_file:
      - .env
    networks:
      - event-world-network
    command: sh -c "npm install && npm start"
  nginx:
    restart: always
    build: ./nginx/
    volumes:
      - ./nginx/ssl/key.pem:/root/ssl/key.pem
      - ./nginx/ssl/cert.pem:/root/ssl/cert.pem
      - ./logs/nginx:/var/log/nginx/
    ports:
      - "443:443"
    depends_on:
      - backend
      - frontend
      - mongo
      - mongo-express
    networks:
      - event-world-network
  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    networks:
      - event-world-network
    volumes:
      - ./data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    networks:
      - event-world-network
    depends_on:
      - mongo

  cypress:
    image: cypress/included:latest
    command: "--browser chrome"
    depends_on:
      - frontend
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    environment:
      - CYPRESS_username=billy
      - CYPRESS_email=billy@domain.ru
      - CYPRESS_password=secret
    networks:
      - event-world-network